language: c++
compiler: clang
env: CMAKE_BUILD_TYPE=RELEASE

branches:
    only:
        - master
        - travis

os:
    - linux
    - osx

osx_image: xcode8.2
sudo: true

before_install: |
    wget http://www.openssl.org/source/openssl-1.1.0e.tar.gz
    tar xzvf openssl-1.1.0e.tar.gz
    cd openssl-1.1.0e
    ./config
    make
    sudo make install
    cd ..

    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update
        brew install jpeg-turbo
        export CMAKE_CXX_COMPILER=clang++
    fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        curl -sSL 'http://llvm.org/apt/llvm-snapshot.gpg.key' | sudo -E apt-key add -
        echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.8 main' | sudo tee -a /etc/apt/sources.list > /dev/null
        sudo -E apt-add-repository -y 'ppa:ubuntu-toolchain-r/test'
        sudo -E apt-add-repository -y 'ppa:kalakris/cmake'
        sudo -E apt-add-repository -y "ppa:boost-latest/ppa"
        sudo apt-get update
        sudo apt-get install --force-yes \
            cmake \
            clang-3.8 \
            libboost1.55-dev \
            libboost-filesystem1.55-dev \
            libboost-locale1.55-dev \
            libssl-dev \
            libpng-dev \
            libjpeg-dev
        export CMAKE_CXX_COMPILER=clang++-3.8
    fi

script: |
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} .. || exit 1
    cmake --build . || exit 1
    cd ..
    ./build/run_tests
